#!/usr/bin/env python3
"""
First-Run Setup Wizard
======================
Two-bot architecture - no direct networking between machines.
Telegram acts as the message relay between Machine A and Machine B.

  Machine A - OpenClaw AI Bot  (@openclawbot)
    - Generates emails
    - Sends approval requests to Machine B's bot via Telegram
    - Receives decline callbacks via its own bot's incoming messages

  Machine B - Approval Bot  (@approvalbot)
    - Shows email preview with ✅ / ❌ buttons
    - ✅ sends via Gmail API
    - ❌ sends a signed decline message to Machine A's bot

Usage:
  python setup.py --machine a    # Configure Machine A (OpenClaw AI Bot)
  python setup.py --machine b    # Configure Machine B (Approval Bot + Gmail)
"""

import argparse
import getpass
import hmac
import hashlib
import json
import os
import re
import secrets
import sys
from pathlib import Path

# ── Colour helpers ────────────────────────────────────────────────────────────
RESET  = "\033[0m"
BOLD   = "\033[1m"
GREEN  = "\033[32m"
YELLOW = "\033[33m"
RED    = "\033[31m"
CYAN   = "\033[36m"

def info(msg):    print(f"{CYAN}ℹ  {msg}{RESET}")
def ok(msg):      print(f"{GREEN}✔  {msg}{RESET}")
def warn(msg):    print(f"{YELLOW}⚠  {msg}{RESET}")
def err(msg):     print(f"{RED}✖  {msg}{RESET}")
def heading(msg): print(f"\n{BOLD}{msg}{RESET}\n{'─' * len(msg)}")


# ── Input helpers ─────────────────────────────────────────────────────────────
def prompt(label: str, default: str = "", secret: bool = False, validator=None) -> str:
    while True:
        display = f"{BOLD}{label}{RESET}"
        if default:
            display += f" [{default}]"
        display += ": "
        value = (getpass.getpass(display) if secret else input(display)).strip()
        if not value:
            value = default
        if not value:
            warn("This field is required.")
            continue
        if validator:
            error = validator(value)
            if error:
                warn(error)
                continue
        return value


def prompt_yes_no(label: str, default: bool = True) -> bool:
    hint   = "[Y/n]" if default else "[y/N]"
    answer = input(f"{BOLD}{label}{RESET} {hint}: ").strip().lower()
    return default if not answer else answer in ("y", "yes")


# ── Validators ────────────────────────────────────────────────────────────────
def validate_bot_token(t):
    if not re.match(r"^\d+:[A-Za-z0-9_-]{35,}$", t):
        return "Expected format: 123456789:ABCdef..."

def validate_chat_id(c):
    if not re.match(r"^-?\d+$", c):
        return "Chat ID must be numeric (e.g. 987654321)"

def validate_email(e):
    if "@" not in e or "." not in e.split("@")[-1]:
        return "Doesn't look like a valid email address"


# ── .env helpers ──────────────────────────────────────────────────────────────
def write_env(path: Path, values: dict):
    lines = ["# Auto-generated by setup.py - do not commit this file\n"]
    for key, val in values.items():
        lines.append(f"{key}={val}\n")
    path.write_text("".join(lines))
    path.chmod(0o600)
    ok(f"Written {path}  (mode 600)")


def load_env(path: Path) -> dict:
    if not path.exists():
        return {}
    out = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            out[k.strip()] = v.strip()
    return out


# ── Telegram helpers ──────────────────────────────────────────────────────────
def _tg_call(token: str, method: str, **kwargs) -> dict:
    try:
        import urllib.request
        url  = f"https://api.telegram.org/bot{token}/{method}"
        data = json.dumps(kwargs).encode() if kwargs else None
        req  = urllib.request.Request(
            url, data=data,
            headers={"Content-Type": "application/json"} if data else {},
        )
        with urllib.request.urlopen(req, timeout=10) as r:
            return json.loads(r.read())
    except Exception as e:
        return {"ok": False, "description": str(e)}


def verify_bot_token(token: str) -> tuple[bool, str]:
    r = _tg_call(token, "getMe")
    return (True, r["result"].get("username", "?")) if r.get("ok") else (False, r.get("description", ""))


def send_test_message(token: str, chat_id: str, text: str) -> tuple[bool, str]:
    r = _tg_call(token, "sendMessage", chat_id=int(chat_id), text=text)
    return (True, "") if r.get("ok") else (False, r.get("description", ""))


def get_bot_chat_id(token: str) -> tuple[bool, str]:
    """
    Gets the bot's own user ID from getMe - used so Machine A knows
    what chat_id to send messages to Machine B's bot.
    """
    r = _tg_call(token, "getMe")
    if r.get("ok"):
        return True, str(r["result"]["id"])
    return False, r.get("description", "")


# ── Gmail OAuth ───────────────────────────────────────────────────────────────
def run_gmail_oauth(credentials_path: str, token_path: str):
    try:
        from google_auth_oauthlib.flow import InstalledAppFlow
    except ImportError:
        err("google-auth-oauthlib not installed. Run: pip install -r requirements.txt")
        sys.exit(1)
    flow  = InstalledAppFlow.from_client_secrets_file(
        credentials_path, ["https://www.googleapis.com/auth/gmail.send"]
    )
    info("Opening browser for Gmail authorisation...")
    creds = flow.run_local_server(port=0)
    p = Path(token_path)
    p.write_text(creds.to_json())
    p.chmod(0o600)
    ok(f"Gmail token saved to {token_path}  (mode 600)")


# ── Machine A setup ───────────────────────────────────────────────────────────
def setup_machine_a():
    heading("Machine A - OpenClaw AI Bot Setup")
    env_path = Path(".env")
    existing = load_env(env_path)

    print("Machine A runs your OpenClaw AI bot. It generates emails and sends")
    print("approval requests to Machine B via Telegram. It listens for decline")
    print("callbacks on its own bot - no public endpoint needed.\n")

    # Own bot token (OpenClaw bot)
    heading("Step 1 / 4 - OpenClaw Bot Token")
    info("This is the token for YOUR AI bot (@openclawbot or similar).")
    info("Create it via @BotFather if you haven't already.")
    while True:
        own_token = prompt("OpenClaw bot token", default=existing.get("OWN_BOT_TOKEN", ""),
                           secret=True, validator=validate_bot_token)
        info("Verifying...")
        valid, name = verify_bot_token(own_token)
        if valid:
            ok(f"Token valid - bot: @{name}")
            break
        err(f"Rejected: {name}")
        if not prompt_yes_no("Try again?"):
            sys.exit(1)

    # Owner chat ID - so Machine A knows who to notify
    heading("Step 2 / 4 - Your Telegram Chat ID")
    info("Machine A needs your chat ID to forward any status messages to you.")
    info("Get it from @userinfobot.")
    while True:
        owner_chat_id = prompt("Your Telegram chat ID",
                               default=existing.get("OWNER_CHAT_ID", ""),
                               validator=validate_chat_id)
        info("Sending test message via OpenClaw bot...")
        valid, error = send_test_message(own_token, owner_chat_id,
                                         "✅ OpenClaw bot connected successfully!")
        if valid:
            ok("Test message sent!")
            break
        err(f"Failed: {error}")
        warn("Make sure you've sent /start to your OpenClaw bot first.")
        if not prompt_yes_no("Try again?"):
            sys.exit(1)

    # Approval bot's chat ID (Machine B's bot)
    heading("Step 3 / 4 - Approval Bot Chat ID")
    info("Machine A sends approval requests TO Machine B's bot.")
    info("You need the numeric user ID of Machine B's bot (@approvalbot).")
    info("Two ways to get it:")
    print("  a) Run setup.py --machine b first - it will print the bot ID")
    print("  b) Forward a message from @approvalbot to @userinfobot\n")
    approval_bot_chat_id = prompt(
        "Approval bot's Telegram user ID",
        default=existing.get("APPROVAL_BOT_CHAT_ID", ""),
        validator=validate_chat_id,
    )

    # Shared secret
    heading("Step 4 / 4 - Shared HMAC Secret")
    existing_ws = existing.get("WEBHOOK_SECRET", "")
    if existing_ws:
        info("Existing WEBHOOK_SECRET found.")
        webhook_secret = existing_ws if prompt_yes_no("Keep it?") else secrets.token_hex(32)
    else:
        webhook_secret = secrets.token_hex(32)

    ok("WEBHOOK_SECRET:")
    print(f"\n  {BOLD}{webhook_secret}{RESET}\n")
    warn("Copy this exact value into Machine B's .env WEBHOOK_SECRET.")
    input(f"{BOLD}Press Enter once you've noted it...{RESET} ")

    write_env(env_path, {
        "OWN_BOT_TOKEN":        own_token,
        "OWNER_CHAT_ID":        owner_chat_id,
        "APPROVAL_BOT_CHAT_ID": approval_bot_chat_id,
        "WEBHOOK_SECRET":       webhook_secret,
    })

    print()
    ok("Machine A setup complete! Start with:")
    print(f"  {BOLD}python ai_app.py{RESET}")


# ── Machine B setup ───────────────────────────────────────────────────────────
def setup_machine_b():
    heading("Machine B - Approval Bot + Gmail Sender Setup")
    env_path = Path(".env")
    existing = load_env(env_path)

    print("Machine B runs the Telegram approval bot and Gmail sender.")
    print("It never shares credentials or network access with Machine A.")
    print("Telegram is the only relay between the two machines.\n")

    # Approval bot token
    heading("Step 1 / 5 - Approval Bot Token")
    info("This is a SEPARATE bot from the OpenClaw bot on Machine A.")
    info("Create a new bot via @BotFather (/newbot).")
    while True:
        own_token = prompt("Approval bot token", default=existing.get("OWN_BOT_TOKEN", ""),
                           secret=True, validator=validate_bot_token)
        info("Verifying...")
        valid, name = verify_bot_token(own_token)
        if valid:
            ok(f"Token valid - bot: @{name}")
            # Print the bot's numeric ID so Machine A setup can use it
            id_ok, bot_id = get_bot_chat_id(own_token)
            if id_ok:
                print()
                info(f"This bot's numeric ID is: {BOLD}{bot_id}{RESET}")
                warn("You'll need this value for Machine A's APPROVAL_BOT_CHAT_ID.")
                input(f"{BOLD}Press Enter once you've noted the bot ID...{RESET} ")
            break
        err(f"Rejected: {name}")
        if not prompt_yes_no("Try again?"):
            sys.exit(1)

    # Owner chat ID
    heading("Step 2 / 5 - Your Telegram Chat ID")
    info("Machine B sends approval previews to your personal Telegram chat.")
    info("Get your chat ID from @userinfobot.")
    while True:
        owner_chat_id = prompt("Your Telegram chat ID",
                               default=existing.get("OWNER_CHAT_ID", ""),
                               validator=validate_chat_id)
        info("Sending test message via approval bot...")
        valid, error = send_test_message(own_token, owner_chat_id,
                                         "✅ Approval bot connected successfully!")
        if valid:
            ok("Test message sent!")
            break
        err(f"Failed: {error}")
        warn("Make sure you've sent /start to the approval bot first.")
        if not prompt_yes_no("Try again?"):
            sys.exit(1)

    # OpenClaw bot's chat ID (Machine A's bot)
    heading("Step 3 / 5 - OpenClaw Bot Chat ID")
    info("When you decline an email, Machine B sends a message TO Machine A's bot.")
    info("You need the numeric user ID of @openclawbot.")
    info("Get it by forwarding a message from @openclawbot to @userinfobot.")
    openclaw_bot_chat_id = prompt(
        "OpenClaw bot's Telegram user ID",
        default=existing.get("OPENCLAW_BOT_CHAT_ID", ""),
        validator=validate_chat_id,
    )

    # Shared webhook secret
    heading("Step 4 / 5 - Shared HMAC Secret")
    info("Paste the WEBHOOK_SECRET generated on Machine A.")
    webhook_secret = prompt("WEBHOOK_SECRET", default=existing.get("WEBHOOK_SECRET", ""), secret=True)

    # Gmail OAuth
    heading("Step 5 / 5 - Gmail Account + OAuth")
    gmail_from = prompt("Gmail address to send from",
                        default=existing.get("GMAIL_FROM", ""),
                        validator=validate_email)
    token_path = prompt("Path to store Gmail OAuth token",
                        default=existing.get("GMAIL_TOKEN_FILE", "token.json"))

    if Path(token_path).exists():
        info(f"{token_path} already exists.")
        redo = prompt_yes_no("Re-run Gmail OAuth flow?", default=False)
    else:
        redo = True

    if redo:
        print()
        info("You need credentials.json from Google Cloud Console:")
        print("  1. https://console.cloud.google.com/ → your project")
        print("  2. APIs & Services → Enable Gmail API")
        print("  3. OAuth consent screen → add your Gmail as a test user")
        print("  4. Credentials → Create OAuth 2.0 Client ID (Desktop app)")
        print("  5. Download JSON → save as credentials.json here\n")
        creds_path = prompt("Path to credentials.json", default="credentials.json")
        if not Path(creds_path).exists():
            err(f"{creds_path} not found. Download it first.")
            sys.exit(1)
        run_gmail_oauth(creds_path, token_path)

    write_env(env_path, {
        "OWN_BOT_TOKEN":        own_token,
        "OWNER_CHAT_ID":        owner_chat_id,
        "OPENCLAW_BOT_CHAT_ID": openclaw_bot_chat_id,
        "WEBHOOK_SECRET":       webhook_secret,
        "GMAIL_FROM":           gmail_from,
        "GMAIL_TOKEN_FILE":     token_path,
    })

    print()
    ok("Machine B setup complete! Start with:")
    print(f"  {BOLD}python approval_bot.py{RESET}")


# ── Entry point ───────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="First-run setup wizard.")
    parser.add_argument("--machine", choices=["a", "b"], required=True,
                        help="'a' = OpenClaw AI Bot  |  'b' = Approval Bot + Gmail")
    args = parser.parse_args()

    print(f"\n{BOLD}{'=' * 55}")
    print("  Email Approval Bot - First-Run Setup Wizard")
    print(f"{'=' * 55}{RESET}")
    print("Secrets are written to .env (mode 600) and never")
    print("stored in source code or shown after confirmation.\n")

    if args.machine == "a":
        setup_machine_a()
    else:
        setup_machine_b()


if __name__ == "__main__":
    main()
