// Package config handles .env file loading and configuration.
package config

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// LoadEnv loads environment variables from a .env file.
func LoadEnv(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	env := make(map[string]string)
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		env[key] = value
	}
	return env, scanner.Err()
}

// WriteEnv writes environment variables to a .env file with mode 0600.
func WriteEnv(path string, values map[string]string) error {
	return Write(path, values)
}

// Write writes environment variables to a .env file with mode 0600.
func Write(path string, values map[string]string) error {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintln(file, "# Auto-generated by glawmail setup - do not commit this file")
	for key, value := range values {
		fmt.Fprintf(file, "%s=%s\n", key, value)
	}
	return nil
}

// MachineAConfig holds Machine A configuration.
type MachineAConfig struct {
	OwnBotToken string
	OwnerChatID string
}

// LoadMachineAConfig loads Machine A configuration from .env.
func LoadMachineAConfig(envPath string) (*MachineAConfig, error) {
	env, err := LoadEnv(envPath)
	if err != nil {
		return nil, fmt.Errorf("loading .env: %w", err)
	}

	required := []string{"OWN_BOT_TOKEN", "OWNER_CHAT_ID"}
	var missing []string
	for _, key := range required {
		if env[key] == "" {
			missing = append(missing, key)
		}
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("missing env vars: %s", strings.Join(missing, ", "))
	}

	return &MachineAConfig{
		OwnBotToken: env["OWN_BOT_TOKEN"],
		OwnerChatID: env["OWNER_CHAT_ID"],
	}, nil
}

// MachineBConfig holds Machine B configuration.
type MachineBConfig struct {
	OwnBotToken          string
	OwnerChatID          string
	GmailFrom            string
	GmailCredentialsFile string
	GmailTokenFile       string
}

// LoadMachineBConfig loads Machine B configuration from .env.
func LoadMachineBConfig(envPath string) (*MachineBConfig, error) {
	env, err := LoadEnv(envPath)
	if err != nil {
		return nil, fmt.Errorf("loading .env: %w", err)
	}

	required := []string{"OWN_BOT_TOKEN", "OWNER_CHAT_ID", "GMAIL_FROM", "GMAIL_CREDENTIALS_FILE", "GMAIL_TOKEN_FILE"}
	var missing []string
	for _, key := range required {
		if env[key] == "" {
			missing = append(missing, key)
		}
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("missing env vars: %s", strings.Join(missing, ", "))
	}

	return &MachineBConfig{
		OwnBotToken:          env["OWN_BOT_TOKEN"],
		OwnerChatID:          env["OWNER_CHAT_ID"],
		GmailFrom:            env["GMAIL_FROM"],
		GmailCredentialsFile: env["GMAIL_CREDENTIALS_FILE"],
		GmailTokenFile:       env["GMAIL_TOKEN_FILE"],
	}, nil
}
