// Package config handles .env file loading and configuration.
package config

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// LoadEnv loads environment variables from a .env file.
func LoadEnv(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() {
		_ = file.Close()
	}()

	env := make(map[string]string)
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		env[key] = value
	}
	return env, scanner.Err()
}

// Write writes environment variables to a .env file with mode 0600.
func Write(path string, values map[string]string) error {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	defer func() {
		_ = file.Close()
	}()

	_, _ = fmt.Fprintln(file, "# Auto-generated by glawmail setup - do not commit this file")
	for key, value := range values {
		_, _ = fmt.Fprintf(file, "%s=%s\n", key, value)
	}
	return nil
}

// Config holds the bot configuration.
type Config struct {
	BotToken             string
	OwnerChatID          string
	GmailFrom            string
	GmailCredentialsFile string
	GmailTokenFile       string
}

// Load loads configuration from .env.
func Load(envPath string) (*Config, error) {
	env, err := LoadEnv(envPath)
	if err != nil {
		return nil, fmt.Errorf("loading .env: %w", err)
	}

	required := []string{
		"BOT_TOKEN",
		"OWNER_CHAT_ID",
		"GMAIL_FROM",
		"GMAIL_CREDENTIALS_FILE",
		"GMAIL_TOKEN_FILE",
	}
	var missing []string
	for _, key := range required {
		if env[key] == "" {
			missing = append(missing, key)
		}
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("missing env vars: %s", strings.Join(missing, ", "))
	}

	return &Config{
		BotToken:             env["BOT_TOKEN"],
		OwnerChatID:          env["OWNER_CHAT_ID"],
		GmailFrom:            env["GMAIL_FROM"],
		GmailCredentialsFile: env["GMAIL_CREDENTIALS_FILE"],
		GmailTokenFile:       env["GMAIL_TOKEN_FILE"],
	}, nil
}
